import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="night">
      <body className={inter.className}>
        <div className="drawer drawer-end">
          <input id="my-drawer-3" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col">
            {/* Navbar */}
            <div className="navbar bg-base-300 w-full md:px-10 fixed z-10">
              <div className="mx-2 flex-1 text-xl md:text-3xl font-extrabold">
                <Link href="/">Debnews</Link>
              </div>
              <div className="hidden flex-none lg:block">
                <ul className="menu menu-horizontal font-semibold">
                  {/* Navbar menu content here */}
                  <li>
                    <Link href={"/category/Games"}>Games</Link>
                  </li>
                  <li>
                    <Link href={"/category/Gadgets"}>Gadgets</Link>
                  </li>
                  <li>
                    <Link href={"/category/Movies"}>Movies</Link>
                  </li>
                  <li>
                    <Link href={"/category/Tech"}>Tech</Link>
                  </li>
                  <li>
                    <a>Trending</a>
                  </li>
                </ul>
              </div>
              <div className="flex-none lg:hidden">
                <label
                  htmlFor="my-drawer-3"
                  aria-label="open sidebar"
                  className="btn btn-square btn-ghost">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    className="inline-block h-6 w-6 stroke-current">
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="2"
                      d="M4 6h16M4 12h16M4 18h16"></path>
                  </svg>
                </label>
              </div>
            </div>
            {/* Page content here */}
            <main className="px-4 mt-20 sm:px-12 xl:px-24">{children}</main>
          </div>
          <div className="drawer-side z-20">
            <label
              htmlFor="my-drawer-3"
              aria-label="close sidebar"
              className="drawer-overlay"></label>
            <ul className="menu bg-base-200 min-h-full w-64 p-4">
              {/* Sidebar content here */}
              <li>
                <a>Sidebar Item 1</a>
              </li>
              <li>
                <a>Sidebar Item 2</a>
              </li>
            </ul>
          </div>
        </div>
        <footer className="mt-12 bg-secondary w-full h-[200px] flex justify-center items-center">
          <p className="text-center text-3xl font-extrabold">Footer</p>
        </footer>
      </body>
    </html>
  );
}
